### ISSUE TITLE
Trying to open ruined portal chest crashes the game. 

### ISSUE THREAD

**Issue by jonask028** [Fourmisain/AxesAreWeapons#11]
Version 1.19.3, quilt mod loader with quilt fabric api installed in a singleplayer world. Error log is [here](https://mclo.gs/loQnvSZ), seems to be a missing field error.

**Comment by jonask028** [comment]
I also have experimental features enabled, but those don't interact with ruined portal chests as far as im aware.

**Comment by jonask028** [comment]
Oh and disabling the mod did allow me to open the chest, the chest had an unbreaking 2 axe and some enchanted boots.

**Comment by Fourmisain** [comment]
Can confirm!
No idea how I missed that one, I did test item enchanting but didn't run into this obvious crash - time to do a proper 1.19.3 release.

...

Aaand...

There we go, 1.6.4 is up!

**Comment by kjonas697** [comment]
Amazing thank you!!
