### ISSUE TITLE
Compatibility error with Enchanting Tweaks mod made by kpzip.

### ISSUE THREAD

**Issue by Pdqih** [Fourmisain/AxesAreWeapons#15]
[crash-2023-11-04_11.47.43-client.txt](https://github.com/Fourmisain/AxesAreWeapons/files/13256434/crash-2023-11-04_11.47.43-client.txt)

Caused by: java.lang.NullPointerException: Cannot read field "enableLootingForRangedWeapons" because "io.github.fourmisain.axesareweapons.common.AxesAreWeaponsCommon.CONFIG" is null

**Comment by Fourmisain** [comment]
Fixed via d4e41c222dfb75febd4b5ca8746779f9455588b9, new version 1.7.2 is up!

**Comment by Pdqih** [comment]
> Fixed via [d4e41c2](https://github.com/Fourmisain/AxesAreWeapons/commit/d4e41c222dfb75febd4b5ca8746779f9455588b9), new version 1.7.2 is up!

Thanks!
