### ISSUE TITLE
[1.21 Fabric] World crashes to menu in single player

### ISSUE THREAD

**Issue by ADVENTdev** [Fourmisain/AxesAreWeapons#17]
Hi, I was playing 1.21 single player with the current 1.21 version of this mod enabled, but when I loaded in a Mansion, the game would buffer momentarily before disconnecting me from my world. It would show the "Server closed." screen with the only option being "Return to Server Listing" despite me playing single player. Occasionally, my logs wouldn't even record the crash's error, which made it even more difficult to figure out which mod was causing this error.

Attached is a log with the disconnection error (all the other logs stopped recording before the disconnection occurred so this is the only one I have).

[2024-08-03-5.log](https://github.com/user-attachments/files/16482641/2024-08-03-5.log)

Hopefully that's enough to work with, but I can answer any further questions if necessary.

**Comment by Fourmisain** [comment]
Dang, that's a critical issue!
I think I understand what's happening but am not sure how to fix it yet.
Will see what I can do and push an update soon hopefully.

**Comment by Fourmisain** [comment]
Okay, this should be fixed in 1.9.1!
