### ISSUE TITLE
Hoes with Sharpness V does not boost its damage

### ISSUE THREAD

**Issue by KienNgoQwert** [Fourmisain/AxesAreWeapons#18]
my netherite hoe stayed 4 damage

**Comment by Fourmisain** [comment]
If you mean the damage value in the tooltip, that's normal vanilla behavior:

![sword1](https://github.com/user-attachments/assets/5d68ec81-7af1-4d7f-9799-e94ce4f20643)
![sword2](https://github.com/user-attachments/assets/fc7a9b9e-8ac4-4c58-86fb-91ad37b9d9c1)

The weapon will still deal more damage when attacking. I just one-shot a cow with a sharpness 100 hoe.

**Comment by KienNgoQwert** [comment]
weird, i tested it against another player and its still 4

**Comment by Fourmisain** [comment]
How exactly did you test the damage?

Also, what version are you on? Any other mods?

**Comment by KienNgoQwert** [comment]
1. Ask a guy to take off his armor to test the damage, he said it took 2 hearts (4 damage)
2. 1.21 Quilt (0.26.4 beta-5 i think?)
3. Only performance mods, AAW is installed only server-side tho

**Comment by Fourmisain** [comment]
Hm... not sure what's happening then. Axes Are Weapons doesn't actually modify Sharpness or the actual damage, it only makes the item enchantable (and changes the durability loss), so you should get the exact same result with a give command like
`/give @a netherite_hoe[minecraft:enchantments={sharpness:5}]`
on a vanilla server.

Gonna try if I can reproduce this.

**Comment by KienNgoQwert** [comment]
if it helps, apparently sharpness 10 does boost damage, but 5 does nada

**Comment by Fourmisain** [comment]
Hold on!
Vanilla hoes only deal 1 damage in vanilla, [even Netherite ones](https://minecraft.wiki/w/Netherite_Hoe#Weapon).

Sharpness V will increase that damage by [`0.5 * level + 0.5`](https://minecraft.wiki/w/Sharpness#Usage) = 3, so we're up to 4.
In other words, everything is working as expected!

**Comment by Fourmisain** [comment]
I should say:
The "All Tools Are Weapons" options are mainly meant to be used in conjunction with other mods that change combat mechanics of those tools. It's basically just one piece of the puzzle.

**Comment by KienNgoQwert** [comment]
oh thank you i misread the stats

**Comment by Fourmisain** [comment]
P.S.
I think in 1.21 it is also possible to change the damage of hoes via a datapack (e.g. by modifying the item's `damage` component) if you so wish.

k, gonna see this issue as resolved!
