### ISSUE TITLE
[1.19] Error loading mod on Forge 41.0.96 

### ISSUE THREAD

**Issue by Baggytrousers27** [Fourmisain/AxesAreWeapons#6]
Axes Are Weapons (axesareweapons) has failed to load correctly
java.lang.reflect.InvocationTargetException: null

[Crashlog](https://pastebin.com/WXafQSr3)

**Comment by Fourmisain** [comment]
Ugh... Did they break the API _again_? Without bumping the even the minor version? I'm mad.

I just did some testing, the mod works fine on Forge 41.0.93 but not on 41.0.94+.
I'm actually not sure if this is intentional on their side - I assume so, but I need to look into it.

**Comment by Fourmisain** [comment]
This is due to https://github.com/MinecraftForge/MinecraftForge/pull/8840, a bunch of Forge classes were renamed - looks like I need to do a separate release for Forge 1.19 afterall - if they don't push this to 1.18 too...
