### ISSUE TITLE
[1.19.2 FORGE] = Crash when using Diamond Pickaxe on clay

### ISSUE THREAD

**Issue by ToxinZangoose** [Fourmisain/AxesAreWeapons#7]
Forge version: 43.1.41
Minecraft version: 1.19.2

Below is the crash log for the singleplayer instance.

[crash-2022-10-14_12.38.07-client.txt]

(https://github.com/Fourmisain/AxesAreWeapons/files/9788861/crash-2022-10-14_12.38.07-client.txt)

**Comment by Fourmisain** [comment]
Still not sure what caused this, there's tons of mods doing stuff in this area in your log but this should be fixed in 1.6.1.
