### ISSUE TITLE
[1.19.2-1.6.0+] Mod causes player to be unable to successfully mine blocks with hands or tools. (Forge version)

### ISSUE THREAD

**Issue by Thombias** [Fourmisain/AxesAreWeapons#8]
Hi there!
So i've encountered a weird issue with your mod. For unknown reasons the MC 1.19.2 forge version of your mod causes me to not be able to mine blocks and get their drops. It's as if i lack the effective tool to mine them, like how it takes forever to mine stone with hands and you get no drops. But in this case i get this behaviour applied to literally every block, even on blocks that should drop from being broken by hands. When i removed your mod the issue was nowhere to be seen. Unfortunately i can't provide crash logs because the game doesn't crash, the same goes for the log file unfortunately, nothing was documented there as far as i'm aware.

What's even stranger though is that the 1.18.2 version is running perfectly fine. I don't have that issue there. I'm running many mods on both 1.18.2 as well as 1.19.2. If this is some incompatibility with other mods i'm unaware of i can provide you my mod list, if required.

Tested on these versions:
MC 1.19.2
Forge 43.1.43
Mod version 1.6.0 & 1.6.1
Issue present on both mod versions

MC 1.18.2
Forge 40.1.84
Mod version 1.6.0
Works just fine

**Comment by Fourmisain** [comment]
Just realized this while trying to sleep, woke me right up. Should be fixed in 1.6.2.
Terribly sorry about that!

Here's the [Modrinth link](https://modrinth.com/mod/axes-are-weapons/version/1.6.2-forge-1.19) if you don't wanna wait for CurseForge approval.

**Comment by Thombias** [comment]
No need to apologize mate, it's fine. Everyone makes mistakes at some point. ;)
Didn't mean to wake you up though, sorry about that!

**Comment by Fourmisain** [comment]
> Didn't mean to wake you up though, sorry about that!

Haha, don't worry, it was my programmer brain that woke me up, asking what I was doing.
